### ISSUE TITLE
Unable to run tests

### ISSUE THREAD

**Issue by tuscland** [binghe/OSCAR#1]
Hi,

I'd like to run OSCAR on LispWorks 7.1.
Loading the system works well, however I'm unable to find the files mentionned in the README.

Cam

**Comment by binghe** [comment]
Hi Cam, sorry, some files mentioned in README have been renamed with their original version info removed. Now I’ve updated README, hope this time you can find those files. I confirmed it working at least under LW 7.1 64bit on Mac OS X.

**Comment by tuscland** [comment]
Great, thanks!
